# Gauss Elimination
## Naive Gauss Elimination


Naive Gauss Elimination is a standard method for solving linear system of equations. It is the simplest of all elimination methods and also not suitable for many situations. Although pivoting makes it more stable against roundoff errors and errors introduced due to ill-conditioning of the system, it is still not the method of choice in many commercial applications. 


The elimination methods start with the representation of the linear system in terms of matrices. A $3 \times 3$ system can be represented by the following matrices, 
- The linear system of equations
\begin{gather}
    a_{11}x_1 + a_{12}x_2 + a_{13}x_3 &= b_1 \\
    a_{21}x_1 + a_{22}x_2 + a_{23}x_3 &= b_2 \\
    a_{31}x_1 + a_{32}x_2 + a_{33}x_3 &= b_3 
\end{gather}

- Matrix representation
\begin{gather}
    \begin{pmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33}
    \end{pmatrix}
    \begin{pmatrix}
    x_1 \\
    x_2 \\
    x_3
    \end{pmatrix} = 
    \begin{pmatrix}
    b_1 \\
    b_2 \\
    b_3
    \end{pmatrix}.
\end{gather}

Once the system is written out in the matrix form, we generally try to conmvert the coefficient matrix into an upper triangular form, recording the necessary changes in the right hand matrix too. In order to do that we form an augmented matrix consisting of the columns of the original coefficient matrix and the right hand $b$ column. Then we employ row operations and column operations on the new matrix to convert it into an upper triangular form.


- Augmented matrix
\begin{gather}
\begin{pmatrix}
a_{11} & a_{12} & a_{13} & b_1 \\
a_{21} & a_{22} & a_{23} & b_2 \\
a_{31} & a_{32} & a_{33} & b_3
\end{pmatrix}
\end{gather}

- Upper Triangular form

$$
\begin{pmatrix}
a'_{11} & a'_{12} & a'_{13} & b'_1 \\
0       & a'_{22} & a'_{23} & b'_2 \\
0       & 0       & a'_{33} & b'_3
\end{pmatrix}
$$


The last system can now be easily solved starting from the last equation and the values of $x_i$'s can be calculated by back-substitution. 


## Equation for Back-Substitution
$$
x_i = \frac{b_i^{i-1} - \sum_{j = i+1}^n a_{ij}^{i-1}x_j}{a_{ii}^{i-1}}
$$

Here $i$ goes from $n-1$ upto $1$.

# Code that does Naive Gauss Elimination
The code is essentially a collection of functions.

In [7]:
import numpy as np

def concat(A, b):
    (m, n) = A.shape
    p = b.shape
    C = np.eye(m, n+1, dtype=float)
    for i in range(0,m):
        for j in range(0,n):
            C[i][j] = A[i][j]
        C[i][j+1] = b[i]    
    return C    


def GaussNaive(A, b):
    (m, n) = A.shape
    if (m != n):
        print("Error! Matrix must be square")
    nb = n + 1
    #Aug = np.concatanate((A, b), axis = 1)
    Aug = concat(A, b)
    print(Aug)
    # Forward Elimination
    for k in range(0, n-1):
        for l in range(k+1, n):
            factor = Aug[l][k]/Aug[k][k]
            for o in range(k, nb):
                Aug[l][o] = Aug[l][o] - factor*Aug[k][o]
    print("Aug :=", Aug)
    # Back Substitution
    x = np.zeros((n, 1), dtype=float)
    x[m-1] = Aug[m-1][nb-1]/Aug[m-1][m-1]
    for i in range(n-1, -1, -1):
        for j in range(i+1, n):
            x[i] = (Aug[i][nb-1] - Aug[i][j]*x[j])/Aug[i][i]
            #print(x[i])
            #print("Inside the loop.")
    return x

# Now calling the functions in the code
The whole code as needs to be written in the exam is a combination of both parts.

In [8]:
A = np.array([[3, -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]])
print("A:=", A)
b = np.array([[7.85, -19.3, 71.4]])
c = np.transpose(b)
print("c:=", c)
D = concat(A, c)
print("D:=", D)
for i in range(3):
    #for j in range(3):
        print(c[i][0])

x = GaussNaive(A, c)
print(x)

A:= [[ 3.  -0.1 -0.2]
 [ 0.1  7.  -0.3]
 [ 0.3 -0.2 10. ]]
c:= [[  7.85]
 [-19.3 ]
 [ 71.4 ]]
D:= [[  3.    -0.1   -0.2    7.85]
 [  0.1    7.    -0.3  -19.3 ]
 [  0.3   -0.2   10.    71.4 ]]
7.85
-19.3
71.4
[[  3.    -0.1   -0.2    7.85]
 [  0.1    7.    -0.3  -19.3 ]
 [  0.3   -0.2   10.    71.4 ]]
Aug := [[  3.          -0.1         -0.2          7.85      ]
 [  0.           7.00333333  -0.29333333 -19.56166667]
 [  0.           0.          10.01204188  70.08429319]]
[[ 3.08333333]
 [-2.5       ]
 [ 7.        ]]


# Summary

The above code has two functions: concat(A, b) and GaussNaive(A, b). The GaussNaive function calls concat. It is not called by the actual code. The concat function takes as argument the two matrices A and b and then produces the augmented matrix Aug. The GaussNaive function takes the same two matrices as input and calculates the solution array x. The function uses the forward elimination and back-substitution steps. The driver code defines the A and b matrices and with these as arguments calls the function GaussNaive. The result is printed out at the end.